### ISSUE TITLE
Druck erfolgt immer auf Standard-Drucker

### ISSUE THREAD

**Issue by ghoeffner** [manfred-mueller/DHLabel#3]
Guten Tag,

folgendes Problem. Ich möchte das Label gerne direkt nach dem laden auf einem Label Drucker drucken. Leider ignoriert das Programm den ausgewälten Drucker und druckt nur auf dem Standard-Drucker.
![](http://i.yt.gl/get/44ecc/lophekoaph88.gif)

Getestet durch umstellen des Standarddruckers auf den Labeldrucker: Dann erfolgt der Ausdruck auf dem Labeldrucker. Leider ist das keine dauerhafte Lösung :-( 

Ohne mich tiefer auszukennen, scheint das Problem zu sein, dass im Block unter https://github.com/manfred-mueller/DHLabel/blob/master/Program/Form1.cs#L219 nur .print aufgerufen wird, vorher aber kein Drucker gesetzt wird https://docs.microsoft.com/en-us/dotnet/api/system.drawing.printing.printersettings.printername?view=dotnet-plat-ext-6.0 ?) und der Ausdruck daher auf dem Standarddrucker erfolgt.

**Comment by manfred-mueller** [comment]
Hallo und danke für die ausfühtrlichen Tests!

Ich habe eine neue Version erstellt, welche einen anderen Druckdialog beinhaltet.
Der Drucker wird beim ersten Start abgefragt und kann danach im Menü geändert werden.

**Comment by ghoeffner** [comment]
Vielen Dank, das Drucken in der neuen Version scheint zu funktionieren!

**Comment by manfred-mueller** [comment]
Perfekt!
