### ISSUE TITLE
Label Printer 

### ISSUE THREAD

**Issue by Beastyboy80** [manfred-mueller/DHLabel#4]
Genau so eine Software hab ich gesucht .
Mega cool.

Kann man den Printer nicht fest Auswählen ?
Bei jedem Programmstart ,ist wieder der Standard Drucker ausgewählt .

Ich nutze aber einen Labelprinter 

Gruss

**Comment by manfred-mueller** [comment]
Danke für das Kompliment.
Mit der Version 1.4 kan jetzt über das Menü der Drucker eingestellt werden.

Gruß

Manfred
