### ISSUE TITLE
Label-Printer druckt "leere" Seite

### ISSUE THREAD

**Issue by chrissy25** [manfred-mueller/DHLabel#5]
Hi,

ich nutze den Label-Printer "PL70e-BT" von Nelko.
Wenn ich direkt aus DHL-Label drucke, dann wird nur eine "leere" Seite gedruckt. Es gibt auch keine Fehlermeldung oder ähnliches.

Wenn ich in DHL-Label das Label als PDF speicher, dieses dann mit Chrome öffne und von dort drucke, funktioniert alles super.

**Comment by manfred-mueller** [comment]
Hi,

ich kann leider das Problem nicht nachvollziehen, da ich nur Zugriff auf einen 9142-CDN-Laserdrucker habe,
welcher auf A6-Einzelblatt-Labels ausgelegt ist.

Da ich davon ausgehe, dass Chrome das Label beim Druck automatisch skaliert, kann ich mir nur vorstellen,
dass sich DHLabel nicht mit den Einstellungen des Druckertreibers verträgt.

Im Anhang als Beispiel die Einstellungen meines Druckers:

Sorry, dass ich nicht mehr helfen kann!

![DHLabel-Drucker](https://github.com/manfred-mueller/DHLabel/assets/65389254/3cce712a-04ef-44b0-a913-6d65573ab712)

**Comment by manfred-mueller** [comment]
ohne identisches Testgerät nicht lösbar

**Comment by LmgUSX** [comment]
Guten Tag, 
ich hatte das selbe Problem, hier ein Bug Fix Vorschlag:
 ```
private void PrintLabel(Image label)
        {
            printDocument1 = new PrintDocument();
            // Set the printer name
            string printerName = Properties.Settings.Default.printOn;
            if (string.IsNullOrEmpty(printerName))
            {
                TopMost = false;
                setPrinter();
                printerName = Properties.Settings.Default.printOn;
            }

            if (!string.IsNullOrEmpty(printerName))
            {
                printDocument1.PrinterSettings.PrinterName = printerName;

                printDocument1.DefaultPageSettings.Landscape = true;
                Margins margins = new Margins(12, 0, 15, 0);
                printDocument1.OriginAtMargins = true;
                printDocument1.DefaultPageSettings.Margins = margins;
                ForcePageSize(printDocument1, PaperKind.A6);

                TopMost = false;
                // Set up printing event
                printDocument1.PrintPage += (sender, args) =>
                {
                    Rectangle printRect = args.PageBounds;

                    if ((double)label.Width / label.Height > (double)printRect.Width / printRect.Height)
                    {
                        printRect.Height = (int)((double)label.Height / label.Width * printRect.Width);
                    }
                    else
                    {
                        printRect.Width = (int)((double)label.Width / label.Height * printRect.Height);
                    }

                    args.Graphics.DrawImage(label, printRect);
                };
                // Print
                printDocument1.Print();
                // Restore TopMost setting
                TopMost = cbOntop.Checked;
            }
        }
``` 

Im ursprünglichen Code wurden die Funktionen PrintLabel und PrintPage sowie die Konfiguration für das Papierformat/die Ausrichtung nur ausgeführt, wenn der Druckername nicht den Standardeinstellungen von Windows entsprach. Wenn der Drucker bereits in der Konfiguration hinterlegt war (unter AppData), wurde dieser Teil übersprungen. Daher kam es zu den leeren Seiten.
Viele Grüße
